dnmshoes/carrito/urls.py
from django.conf.urls import url
from . import views

app_name = 'carrito'

urlpatterns = [
    url(r'^$', views.carro_detalle, name='carrito_detalle'),
    url(r'^add/(?P<product_id>\d+)/$', views.carro_agregar, name='carrito_agregar'),
    url(r'^remove/(?P<product_id>\d+)/$', views.carro_remover, name='carrito_remover'),
]

dnmshoes/dnmshoes/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
#from jet.dashboard.dashboard_modules import google_analytics_views

admin.autodiscover()

urlpatterns = [
    #panel de administracion jet
	path('jet/', include('jet.urls', 'jet')),
	path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    path('admin/', admin.site.urls),

    #allauth (cuentas - sesiones - registro)
    path('accounts/', include('allauth.urls')),

    #carrito de compras 
    path('carrito/', include('carrito.urls')),

    #orden de compras
    path('ordenes/', include('orden.urls')),

    #principal
    path('', include('secciones.urls')),
 
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dnmshoes/orden/urls.py
from django.conf.urls import url
from . import views

app_name = 'ordenes'

urlpatterns = [
    url(r'^crear/$', views.crear_orden, name='crear_orden')
]

dnmshoes/secciones/urls.py
from django.conf.urls import url #importamos las urls de django urls
from . import views #importamos los metodos de views.py
from django.urls import path, re_path
from .views import PrincipalView, TiendaView

app_name = 'secciones'

urlpatterns = [
    path('', PrincipalView.as_view(), name='home'),
    path('tienda/', TiendaView.as_view(), name='tienda'),
    #path('categoria/<slug>', CategoriaView.as_view(), name='product_list_by_category'),
    re_path(r'^(?P<category_slug>[-\w]+)/$', views.CategoriaFunc, name='product_list_by_category'),
    re_path(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.product_detail, name='product_detail'),
]

dnmshoes/templates/base.html
<!DOCTYPE html>
<html lang="es">
  <head>
    {% include 'header.html' %}
    <title>BENJAMIN {% block head_title %}{% endblock %}</title>
    {% block extra_head %}
    
    {% endblock %}
  </head>
  <body>
    {% include 'navbar.html' %}
    {% block body %}
<!--message-->
    <div>
      {% if messages %} {% for message in messages %}
      <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    </div>
<!--fin message-->

    {% endfor %} 
    {% endif %} 

    {% block content %}
    {% endblock %}

    {% endblock %}
    

    {% block extra_body %}
    {% endblock %}

    {% include 'footer.html' %}

    {% include 'script.html' %}

    {% block extra_script %}
    {% endblock extra_script %}
  </body>
</html>

dnmshoes/templates/footer.html
{% load static %}
 <footer class="footer-area section_gap">
    <div class="container">
        <div class="row">
                <div class="col-lg-3  col-md-6 col-sm-6">
                    <div class="single-footer-widget" id="nosotros">
                    <h6>About Us</h6>
                        <p>
                            Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt
                            ut labore dolore
                            magna aliqua.
                        </p>
                    </div>
                </div>
            <div class="col-lg-4  col-md-6 col-sm-6">
                <div class="single-footer-widget">
                    <h6>Newsletter</h6>
                    <p>Mantengase actualizado con lo ultimo</p>
                    <div class="" id="mc_embed_signup">

                        <form target="_blank" novalidate="true" action="#"
                            method="get" class="form-inline">

                            <div class="d-flex flex-row">

                                <input class="form-control" name="EMAIL" placeholder="Ingresa tu Email" onfocus="this.placeholder = ''"
                                    onblur="this.placeholder = 'Ingresa tu Email '" required="" type="email">


                                <button class="click-btn btn btn-default"><i class="fa fa-long-arrow-right"
                                        aria-hidden="true"></i></button>
                                <div style="position: absolute; left: -5000px;">
                                    <input name="b_36c4fd991d266f23781ded980_aefe40901a" tabindex="-1" value=""
                                        type="text">
                                </div>

                                <div class="col-lg-4 col-md-4">
                                                <button class="bb-btn btn"><span class="lnr lnr-arrow-right"></span></button>
                                </div>
                            </div>
                            <div class="info"></div>
                        </form>
                    </div>
                </div>
            </div>
            <div class="col-lg-3  col-md-6 col-sm-6">
                <div class="single-footer-widget mail-chimp">
                    <h6 class="mb-20">Instragram</h6>
                    <ul class="instafeed d-flex flex-wrap">
                        <a href="https://www.instagram.com/benjamin.ind/">
                        {% include 'secciones/instagram.html' %}
                        </a>
                    </ul>
                </div>
            </div>
            <div class="col-lg-2 col-md-6 col-sm-6">
                <div class="single-footer-widget" id="contacto">
                    <h6>Siguenos</h6>
                    <p>Nuestras redes sociales</p>
                    <div class="footer-social d-flex align-items-center">
                        <a href="https://www.facebook.com/benjaminindumentaria2/"><i class="ti-facebook"></i></a>
                        <a href="https://twitter.com/?lang=es"><i class="ti-twitter"></i></a>
                        <a href="https://www.instagram.com/benjamin.ind/"><i class="ti-instagram"></i></a>
                    </div>
                </div>
            </div>
        </div>
        
    </div>
</footer>

dnmshoes/templates/header.html
{% load static %}
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no, shrink-to-fit=no">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!--favicon-->
<link rel="apple-touch-icon" sizes="57x57" href="{% static 'img/favicon/apple-icon-57x57.png' %}">
<link rel="apple-touch-icon" sizes="60x60" href="{% static 'img/favicon/apple-icon-60x60.png' %} ">
<link rel="apple-touch-icon" sizes="72x72" href="{% static 'img/favicon/apple-icon-72x72.png' %} ">
<link rel="apple-touch-icon" sizes="76x76" href="{% static 'img/favicon/apple-icon-76x76.png' %}">
<link rel="apple-touch-icon" sizes="114x114" href="{% static 'img/favicon/apple-icon-114x114.png' %}">
<link rel="apple-touch-icon" sizes="120x120" href="{% static 'img/favicon/apple-icon-120x120.png' %}">
<link rel="apple-touch-icon" sizes="144x144" href="{% static 'img/favicon/apple-icon-114x114.png' %}">
<link rel="apple-touch-icon" sizes="152x152" href="{% static 'img/favicon/apple-icon-152x152.png' %}">
<link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/favicon/apple-icon-180x180.png' %}">
<link rel="icon" type="image/png" sizes="192x192"  href="{% static 'img/favicon/android-icon-192x192.png' %}">
<link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/favicon/favicon-32x32.png' %}">
<link rel="icon" type="image/png" sizes="96x96" href="{% static 'img/favicon/favicon-96x96.png' %}">
<link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/favicon/favicon-16x16.png' %}">
<link rel="manifest" href="{% static 'img/favicon/manifest.json' %}">
<meta name="msapplication-TileColor" content="#ffffff">
<meta name="msapplication-TileImage" content="{% static 'img/favicon/ms-icon-144x144.png' %}">
<meta name="theme-color" content="#ffffff">
    <!--fin favicon-->
<meta name="description" content="benjamin indumentaria lorem ipsum" />
    <!--estilos local-->
<link rel="stylesheet" href="{% static 'css/linearicons.css' %}" >
<link rel="stylesheet" href="{% static 'css/themify-icons.css' %}">
<link rel="stylesheet" href="{% static 'css/navbar.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/estilos.css' %}" >
    <!--fin estilos local-->
    <!--estilos cdn-->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css" integrity="sha256-h20CPZ0QyXlBuAw7A+KluUYx/3pK+c7lYEpqLTlxjYQ=" crossorigin="anonymous" />
    <!--fin estilos cdn-->

dnmshoes/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% load slide_template_tags %}
{% load categoria_template_tags %}
{% block extra_head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/estilos.css' %}" >
<link rel="stylesheet" type="text/css" href="{% static 'css/index.css' %}">
<!--===============================================================================================-->
  <link
    rel="stylesheet"
    type="text/css"
    href="{% static 'vendor/animate/animate.css' %}"
  />
  <!--===============================================================================================-->
  <link
    rel="stylesheet"
    type="text/css"
    href="{% static 'vendor/css-hamburgers/hamburgers.min.css' %}"
  />
  <!--===============================================================================================-->
  <link
    rel="stylesheet"
    type="text/css"
    href="{% static 'vendor/animsition/css/animsition.min.css' %}"
  />
  <!--===============================================================================================-->
  <link
    rel="stylesheet"
    type="text/css"
    href="{% static 'vendor/select2/select2.min.css' %}"
  />
  <!--===============================================================================================-->
  <link
    rel="stylesheet"
    type="text/css"
    href="{% static 'vendor/daterangepicker/daterangepicker.css' %}"
  />
  <!--===============================================================================================-->
  <link
    rel="stylesheet"
    type="text/css"
    href="{% static 'vendor/slick/slick.css' %}"
  />
  <!--===============================================================================================-->
  <link
    rel="stylesheet"
    type="text/css"
    href="{% static 'vendor/lightbox2/css/lightbox.min.css' %}"
  />
  <!--===============================================================================================-->
{% endblock %}
{% block content %}
<!--carousel-->

<section class="slide1">
		<div class="wrap-slick1">
			<div class="slick1">
			{% slides %}
			</div>
		</div>
</section>

 <!--categorias-->
<section class="p-40"> 
	<div class="container">			
		<div class="d-flex flex-row justify-content-start">
			{% categorias_div %}
		</div>
	</div>
	
	
	{% comment %} <div class="container">
		<div class="row">
			<div class="col-sm-6 col-md-3 col-lg-3 d-inline-block">    
			<div class="block1 hov-img-zoom pos-relative m-b-30">
				<img src="C:\Users\Matt\Desktop\img\img\banner-02.webp" alt="IMG-BENNER">
				<div class="block1-wrapbtn w-size2">
					<a href="#" class="flex-c-m size2 m-text2 bg3 hov1 trans-0-4">Sunglasses </a>
				</div>
			</div>
			</div>
		
			<div class="col-sm-6 col-md-3 col-lg-3 d-inline-block">    
			<div class="block1 hov-img-zoom pos-relative m-b-30">
				<img src="C:\Users\Matt\Desktop\img\img\banner-03.webp" alt="IMG-BENNER">
				<div class="block1-wrapbtn w-size2">
					<a href="#" class="flex-c-m size2 m-text2 bg3 hov1 trans-0-4">Sunglasses </a>
				</div>
			</div>
			</div>
			<div class="col-sm-6 col-md-3 col-lg-3 d-inline-block">    
			<div class="block1 hov-img-zoom pos-relative m-b-30">
				<img src="C:\Users\Matt\Desktop\img\img\banner-04.webp" alt="IMG-BENNER">
				<div class="block1-wrapbtn w-size2">
					<a href="#" class="flex-c-m size2 m-text2 bg3 hov1 trans-0-4">Sunglasses </a>
				</div>
			</div>
			</div>
			<div class="col-sm-6 col-md-3 col-lg-3 d-inline-block">    
			<div class="block1 hov-img-zoom pos-relative m-b-30">
				<img src="C:\Users\Matt\Desktop\img\img\banner-05.webp" alt="IMG-BENNER">
				<div class="block1-wrapbtn w-size2">
					<a href="#" class="flex-c-m size2 m-text2 bg3 hov1 trans-0-4">Sunglasses </a>
				</div>
			</div>
			</div>
			<div class="col-sm-6 col-md-3 col-lg-3 d-inline-block">    
			<div class="block1 hov-img-zoom pos-relative m-b-30">
				<img src="C:\Users\Matt\Desktop\img\img\banner-07.webp" alt="IMG-BENNER">
				<div class="block1-wrapbtn w-size2">
					<a href="#" class="flex-c-m size2 m-text2 bg3 hov1 trans-0-4">Sunglasses </a>
				</div>
			</div>
			</div>
			<div class="col-sm-6 col-md-3 col-lg-3 d-inline-block">    
			<div class="block1 hov-img-zoom pos-relative m-b-30">
				<img src="C:\Users\Matt\Desktop\img\img\banner-02.webp" alt="IMG-BENNER">
				<div class="block1-wrapbtn w-size2">
					<a href="#" class="flex-c-m size2 m-text2 bg3 hov1 trans-0-4">Sunglasses </a>
				</div>
			</div>
			</div>
		</div>
	</div> {% endcomment %}


	
</section>

<!--productos destacados-->
<!--marcas-->
<section class="logo-marcas">
    <div class="container-fluid text-center">
		<img src="https://cdn.worldvectorlogo.com/logos/adidas-9.svg" class="logos">
		<img src="https://cdn.worldvectorlogo.com/logos/fila-9.svg" class="logos"> 
		<img src="https://cdn.worldvectorlogo.com/logos/nike-3.svg" class="logos"> 
	</div>   
      
</section>

<!-- Instagram -->
<section class="instagram p-t-20 p-b-52">
	<div class="sec-title p-b-52 p-l-15 p-r-15">
		<h3 class="m-text5 t-center">
			@ Seguinos en Instagram
		</h3>
	</div>

	<div class="flex-w">
		<!-- Block4 -->
		<div class="block4 wrap-pic-w">
			<img src="{% static 'img/instagram/insta (1).jpg' %}" alt="IMG-INSTAGRAM">

			<a href="#" class="block4-overlay sizefull ab-t-l trans-0-4">
				<span class="block4-overlay-heart s-text9 flex-m trans-0-4 p-l-40 p-t-25">
					<i class="icon_heart_alt fs-20 p-r-12" aria-hidden="true"></i>
					<span class="p-t-2">39</span>
				</span>

				<div class="block4-overlay-txt trans-0-4 p-l-40 p-r-25 p-b-30">
					<p class="s-text10 m-b-15 h-size1 of-hidden">
						Nullam scelerisque, lacus sed consequat laoreet, dui enim iaculis leo, eu viverra ex nulla in tellus. Nullam nec ornare tellus, ac fringilla lacus. Ut sit amet enim orci. Nam eget metus elit.
					</p>

					<span class="s-text9">
						Photo by @nancyward
					</span>
				</div>
			</a>
		</div>

		<!-- Block4 -->
		<div class="block4 wrap-pic-w">
			<img src="{% static 'img/instagram/insta (2).jpg' %}" alt="IMG-INSTAGRAM">

			<a href="#" class="block4-overlay sizefull ab-t-l trans-0-4">
				<span class="block4-overlay-heart s-text9 flex-m trans-0-4 p-l-40 p-t-25">
					<i class="icon_heart_alt fs-20 p-r-12" aria-hidden="true"></i>
					<span class="p-t-2">39</span>
				</span>

				<div class="block4-overlay-txt trans-0-4 p-l-40 p-r-25 p-b-30">
					<p class="s-text10 m-b-15 h-size1 of-hidden">
						Nullam scelerisque, lacus sed consequat laoreet, dui enim iaculis leo, eu viverra ex nulla in tellus. Nullam nec ornare tellus, ac fringilla lacus. Ut sit amet enim orci. Nam eget metus elit.
					</p>

					<span class="s-text9">
						Photo by @nancyward
					</span>
				</div>
			</a>
		</div>

		<!-- Block4 -->
		<div class="block4 wrap-pic-w">
			<img src="{% static 'img/instagram/insta (3).jpg' %}" alt="IMG-INSTAGRAM">

			<a href="#" class="block4-overlay sizefull ab-t-l trans-0-4">
				<span class="block4-overlay-heart s-text9 flex-m trans-0-4 p-l-40 p-t-25">
					<i class="icon_heart_alt fs-20 p-r-12" aria-hidden="true"></i>
					<span class="p-t-2">39</span>
				</span>

				<div class="block4-overlay-txt trans-0-4 p-l-40 p-r-25 p-b-30">
					<p class="s-text10 m-b-15 h-size1 of-hidden">
						Nullam scelerisque, lacus sed consequat laoreet, dui enim iaculis leo, eu viverra ex nulla in tellus. Nullam nec ornare tellus, ac fringilla lacus. Ut sit amet enim orci. Nam eget metus elit.
					</p>

					<span class="s-text9">
						Photo by @nancyward
					</span>
				</div>
			</a>
		</div>

		<!-- Block4 -->
		<div class="block4 wrap-pic-w">
			<img src="{% static 'img/instagram/insta (4).jpg' %}" alt="IMG-INSTAGRAM">

			<a href="#" class="block4-overlay sizefull ab-t-l trans-0-4">
				<span class="block4-overlay-heart s-text9 flex-m trans-0-4 p-l-40 p-t-25">
					<i class="icon_heart_alt fs-20 p-r-12" aria-hidden="true"></i>
					<span class="p-t-2">39</span>
				</span>

				<div class="block4-overlay-txt trans-0-4 p-l-40 p-r-25 p-b-30">
					<p class="s-text10 m-b-15 h-size1 of-hidden">
						Nullam scelerisque, lacus sed consequat laoreet, dui enim iaculis leo, eu viverra ex nulla in tellus. Nullam nec ornare tellus, ac fringilla lacus. Ut sit amet enim orci. Nam eget metus elit.
					</p>

					<span class="s-text9">
						Photo by @nancyward
					</span>
				</div>
			</a>
		</div>

		<!-- Block4 -->
		<div class="block4 wrap-pic-w">
			<img src="{% static 'img/instagram/insta (5).jpg' %}" alt="IMG-INSTAGRAM">

			<a href="#" class="block4-overlay sizefull ab-t-l trans-0-4">
				<span class="block4-overlay-heart s-text9 flex-m trans-0-4 p-l-40 p-t-25">
					<i class="icon_heart_alt fs-20 p-r-12" aria-hidden="true"></i>
					<span class="p-t-2">39</span>
				</span>

				<div class="block4-overlay-txt trans-0-4 p-l-40 p-r-25 p-b-30">
					<p class="s-text10 m-b-15 h-size1 of-hidden">
						Nullam scelerisque, lacus sed consequat laoreet, dui enim iaculis leo, eu viverra ex nulla in tellus. Nullam nec ornare tellus, ac fringilla lacus. Ut sit amet enim orci. Nam eget metus elit.
					</p>

					<span class="s-text9">
						Photo by @nancyward
					</span>
				</div>
			</a>
		</div>
	</div>
</section>


{% endblock content %}

{% block extra_script %}

<script type="text/javascript" src="{% static 'vendor/slick/slick.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/slick-custom.js' %}"></script>

{% endblock extra_script %}

dnmshoes/templates/navbar.html
{% load static %}
{% load categoria_template_tags %}
<style>
.bg-dark {
  background-color: #000000 !important;
}
</style>
 <!--nav-bar-->
<nav class="navbar webnav navbar-expand-lg navbar-dark bg-dark">

  <a class="navbar-brand" href="{% url 'secciones:home' %}"><img src="{% static 'img/logo.svg' %}" class="logonav" alt="logo"></a>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'secciones:tienda' %}">Tienda<span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#contacto">Contacto</a>
        </li>
        {%categoria%}
    </ul> 
    {% if request.user.is_authenticated %}
      {% if request.user.is_superuser %}
      <ul class="nav navbar-nav ml auto">
        <li class="nav-item">
          <a class="nav-link adm-btn" href="{% url 'admin:index' %}">Admin</a>
        </li>
      </ul>
      {% endif %}
      <ul class="nav navbar-nav ml auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url "carrito:carrito_detalle" %}">
            <i class="lnr lnr-cart">
              {% with total_items=carrito|length %}
                {% if carrito|length > 0 %}
                <span class="badge badge-light">{{total_items}}</span>
                {% endif %}
              {% endwith %}
            </i>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#perfil">
            <i class="lnr lnr-user">
            </i>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'account_logout' %}">Cerrar sesión</a>
        </li>
      </ul>
    {% else %}
      <ul class="nav navbar-nav ml-auto">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown"><b>Iniciar sesión</b> <span class="caret"></span></a>
          <ul id="login-dp" class="dropdown-menu dropdown-menu-right mt-2">
            <li>
              <div class="row">
                  <div class="col-lg-12">
                    <div class="social-buttons">
                      <a href="#" class="btn btn-fb"><i class="fab fa-facebook-f"></i> Facebook</a>
                      <a href="#" class="btn btn-tw"><i class="fab fa-twitter"></i> Twitter</a>
                    </div>
                      <hr>
                      <form class="login" role="form" method="POST" action="{% url 'account_login' %}" accept-charset="UTF-8" id="login-nav">
                        {% csrf_token %}
                        <input type="hidden" name="next" value="{{ request.get_full_path }}" />
                        <tr>
                          <th>
                            <label for="id_login" hidden>Usuario:</label>
                          </th>
                          <td>
                            <div class="form-group">
                              <input type="text" class="form-control" name="login" placeholder="Usuario" autofocus="autofocus" maxlength="150" required id="id_login">
                            </div>
                            {% comment %} <input type="text" name="login" placeholder="Usuario" autofocus="autofocus" maxlength="150" required id="id_login"> {% endcomment %}
                          </td>
                        </tr>
                        <tr>
                          <th>
                            <label for="id_password" hidden>Contraseña:</label>
                          </th>
                          <td>
                          <div class="form-group">
                            <input type="password" class="form-control" name="password" placeholder="Contraseña" required id="id_password">
                          </div>
                            {% comment %} <input type="password" name="password" placeholder="Contraseña" required id="id_password"> {% endcomment %}
                          </td>
                        </tr>
                        <div class="help-block text-right"><a class="button secondaryAction link-dp" href="{% url 'account_reset_password' %}">¿Olvidaste la contraseña?</a></div>
                        <tr>
                          <td>
                            <div class="checkbox">
                              <label for="id_remember"><input type="checkbox" name="remember" id="id_remember">  Recordarme</label>                                          
                            </div>
                          </td>
                        </tr>                        
                        <button class="primaryAction btn btn-primary btn-block login-b" type="submit">Iniciar sesión</button>
                      </form>
                      <div class="bottom container">Nuevo aqui ?<a href="{% url 'account_signup' %}" class="link-dp"><b> Registrate!</b></a>
                      </div>                    
                  </div>
                  
              </div>
            </li>
          </ul>
        </li>
      </ul>   
    {% endif %}
  </div>
</nav>
<!--fin nav bar-->

    {% comment %} <form class="form-inline">
      <!-- {{ request.user }} -->
      {% if request.user.is_authenticated %}
      <div class="input-group">
        <div class="input-group-prepend">
          <!--Carrito de compras-->
          {% with totail_items=carrito|length %}
              {% if carrito|length > 0 %}
                <a href="{% url "carrito:carrito_detalle" %}" class="input-group-text ti-shopping-cart-full">{{ totail_items }}</a>
                <!-- objetos 
                {{ totail_items }}= cantidad de items
                Producto{{ totail_items|pluralize }}
                {{ carrito.get_total_price }}
                -->
              {% else %}
                <span class="input-group-text ti-shopping-cart" id="basic-addon1"></span>
              {% endif %}
          {% endwith %} 
      <!--fin Carrito de compras -->
          <span class="input-group-text ti-user" id="basic-addon1"></span>
        </div>
        <input type="text" class="form-control" placeholder="{{ request.user }}" aria-label="Username" aria-describedby="basic-addon1" disabled>
      </div>
      {% else %}
        <li class="nav-item">
          <a class="nav-link" href="#">Iniciar sesion</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Crear cuenta</a>
        </li> 
      {% endif %}
      
    </form>  {% endcomment %} 

dnmshoes/templates/register.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %} 

  {% block content %}
  <div class="container">

    <div class="card o-hidden border-0 shadow-lg my-5">
      <div class="card-body p-0">
        <!-- Nested Row within Card Body -->
        <div class="row">
          <div class="col-lg-2 d-none d-lg-block"></div>
          <div class="col-lg-8">
            <div class="p-5">
              <div class="text-center">
                <h1 class="h4 text-gray-900 mb-4">Crear una cuenta!</h1>
              </div>
              <form method="POST">
                {% csrf_token %}
                {{form | crispy}}
                <button type="submit" class="btn btn-primary">Enviar</button>
              </form>
              <hr>
              <div class="text-center">
                <a class="small" href="#">¿perdiste la contraseña?</a>
              </div>
              <div class="text-center">
                <a class="small" href="#">¿ya tienes una cuenta? Login!</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

  </div>
  {% endblock content %}

dnmshoes/templates/script.html
{% load static %}
<script src="{% static 'js/jquery-3.3.1.slim.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/bootstrap.min.js' %}" type="text/javascript"></script>