dnmshoes/carrito/urls.py
from django.conf.urls import url
from . import views

app_name = 'carrito'

urlpatterns = [
    url(r'^$', views.carro_detalle, name='carrito_detalle'),
    url(r'^add/(?P<product_id>\d+)/$', views.carro_agregar, name='carrito_agregar'),
    url(r'^remove/(?P<product_id>\d+)/$', views.carro_remover, name='carrito_remover'),
]

dnmshoes/dnmshoes/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
#from jet.dashboard.dashboard_modules import google_analytics_views

admin.autodiscover()

urlpatterns = [
    #panel de administracion jet
	path('jet/', include('jet.urls', 'jet')),
	path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    path('admin/', admin.site.urls),

    #allauth (cuentas - sesiones - registro)
    path('accounts/', include('allauth.urls')),

    #carrito de compras 
    path('carrito/', include('carrito.urls')),

    #orden de compras
    path('ordenes/', include('orden.urls')),

    #principal
    path('', include('secciones.urls')),
 
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dnmshoes/orden/urls.py
from django.conf.urls import url
from . import views

app_name = 'ordenes'

urlpatterns = [
    url(r'^crear/$', views.crear_orden, name='crear_orden')
]

dnmshoes/secciones/urls.py
from django.conf.urls import url #importamos las urls de django urls
from . import views #importamos los metodos de views.py
from django.urls import path, re_path
from .views import PrincipalView, TiendaView

app_name = 'secciones'

urlpatterns = [
    path('', PrincipalView.as_view(), name='home'),
    path('tienda/', TiendaView.as_view(), name='tienda'),
    #path('categoria/<slug>', CategoriaView.as_view(), name='product_list_by_category'),
    re_path(r'^(?P<category_slug>[-\w]+)/$', views.CategoriaFunc, name='product_list_by_category'),
    re_path(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.product_detail, name='product_detail'),
]

dnmshoes/carrito/models.py
from django.db import models

# Create your models here.

dnmshoes/carrito/forms.py
from django import forms


CANTIDAD_OPCIONES_PRODUCTO = [(i, str(i)) for i in range(1, 26)]


class FormAgregarProductoCarrito(forms.Form):
    cantidad = forms.TypedChoiceField(choices=CANTIDAD_OPCIONES_PRODUCTO, coerce=int)
    actualizar = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

dnmshoes/carrito/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from secciones.models import Producto
from .carrito import Carrito
from .forms import FormAgregarProductoCarrito


@require_POST
def carro_agregar(request, product_id):
    carro = Carrito(request)
    product = get_object_or_404(Producto, id_producto=product_id)
    form = FormAgregarProductoCarrito(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        carro.agregar(Producto=product, cantidad=cd['cantidad'], actualizar_cantidad=cd['actualizar'])
    return redirect('carrito:carrito_detalle')


def carro_remover(request, product_id):
    carro = Carrito(request)
    producto = get_object_or_404(Producto, id_producto=product_id)
    carro.remover(producto)
    return redirect('carrito:carrito_detalle')


def carro_detalle(request):
    carro = Carrito(request)
    for item in carro:
        item['form_actualizar_cantidad'] = FormAgregarProductoCarrito(initial={'cantidad': item['cantidad'], 'actualizar': True})
    return render(request, 'carrito/detalle.html', {'carrito': carro})

dnmshoes/carrito/templates/carrito/detalle.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Tu carrito de compras
{% endblock %}


{% block content %}
    <div class="container table-responsive">
        <div class="row" style="margin-top: 6%">
        
            <table class="table table-striped table-hover">
                <thead style="background-color: black">
                    <tr>
                        <th style="color: white;">Imagen</th>
                        <th style="color: white;">Producto</th>
                        <th style="color: white;">Cantidad</th>
                        <th style="color: white;">Remover</th>
                        <th style="color: white;">Precio unitario</th>
                        <th style="color: white;">Precio</th>
                    </tr>
                </thead>
                <tbody>
                {% for item in carrito %}
                    {% with producto=item.producto  %}
                        <tr>
                            <td>
                                <a href="{{ producto.get__absolute_url }}">
                                    <img src="{% if producto.imagen %} {{ producto.imagen.url }} {% else %} {% static 'img/default.svg' %} {% endif %}" alt="..." style="height: 130px; width: auto">
                                </a>
                            </td>
                            <td>{{ producto.Modelo.Marca }} {{ producto.Modelo }}</td>
                            <td>
                                <form action="{% url 'carrito:carrito_agregar' producto.id_producto %}" method="post">
                                    {% csrf_token %}
                                    {{ item.form_actualizar_cantidad.cantidad }}
                                    {{ item.form_actualizar_cantidad.actualizar }}
                                    <input type="submit" value="Actualizar" class="btn btn-info">
                                </form>
                            </td>
                            <td>
                                <a href="{% url 'carrito:carrito_remover' producto.id_producto %}">Remover</a>
                            </td>
                            <td>${{ item.precio }}</td>
                            <td>${{ item.precio_total }}</td>
                        </tr>
                    {% endwith %}
                {% endfor %}
                <tr style="background-color: black">
                    <td><b>Total</b></td>
                    <td colspan="4"></td>
                    <td colspan="num"><b>${{ carrito.get_total_price }}</b></td>
                </tr>
                </tbody>
            </table>
        <p class="text-right">
            <a href="{% url 'secciones:tienda' %}" class="btn btn-default">Continuar comprando</a>
            <a href="{% url 'ordenes:crear_orden' %}" class="btn btn-primary">Confirmar</a>
        </p>
        </div>
    </div>
{% endblock %}